### PR TITLE
Update LandingPage initial content and styles

### PR DESCRIPTION
**Pull request by rmjordas**
TODO:

- [ ] `LandingBanner`
- [ ] `LandingForm`
- [ ] `LandingFeatures`
- [ ] `LandingPricing`
- [ ] `LandingFooter`

### CODE REVIEW

**Comment by rmjordas** [comment]
@rickywid Why did you merge it? It's still in progress

**Comment by rickywid** [comment]
You created a pull request. Also why am I receiving pull requests for your group?

**Comment by rmjordas** [comment]
@rickywid I publish the PR to get comments from my team, it's not done yet.

You're getting notifications because you are watching the repo: https://github.com/projectunic0rn/grocerhub-ui/watchers

**Comment by rickywid** [comment]
I shouldn't be allowed to approve pull requests for your group. I won't approve any of your group's future pull requests. Sorry about that.

**Pull request merged**
